### ISSUE TITLE
good stuff

### ISSUE THREAD

**Issue by eylles** [arkhiwarkhi/Pipewire-on-Devuan#1]
just a small nitpick, the script wire may lead to instances of wireplumber, pipewire and pipewire-pulse dangling after logout.

i'd suggest doing something like:
```sh
#!/usr/bin/env bash
wp_pid=""
pw_pid=""
pp_pid=""

clean_up () {
	kill $wp_pid
	kill $pw_pid
	kill $pp_pid
}

wireplumber &
wp_pid=$!

pipewire &
pw_pid=$!

pipewire-pulse &
pp_pid=$!

trap 'clean_up' EXIT
```

that should capture the process id of every process and kill them when the script exits.

**Comment by arkhiwarkhi** [comment]
Thank you :) much appreciated !

**Comment by eylles** [comment]
@arkhiwarkhi mind you that here "SHOULD" is on capital letters, it may or may not work on your system, back when i tried a solution of a similar nature in mine it didn't work and instead of debugging why it didn't i ended up cobbling together a different [solution](https://github.com/eylles/shed) altogether to terminate every process in the session before logging out.
